name: Security

on:
  workflow_dispatch:   # запуск вручну
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"   # щодня о 03:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  python-deps-audit:
    name: Python dependency audit (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit
        run: pip-audit

  gitleaks-scan:
    name: Secret scanning with gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
