name: Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"  # щодня о 03:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  python-deps-audit:
    name: Python dependency audit (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit (fail on vulns)
        run: |
          pip-audit -r requirements.txt -c constraints.txt --format sarif --output pip-audit.sarif

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif

  secrets-scan:
    name: Secrets scan (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --no-banner --redact --verbose --exit-code 1
