name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Generate SBOM
        run: python scripts/generate_sbom.py

      - name: Compute checksums
        run: |
          shasum -a 256 dist/* provenance/sbom.spdx.json > CHECKSUMS.SHA256

      - name: Generate signing key
        run: |
          gpg --batch --passphrase '' --quick-gen-key "CI <ci@example.com>" default default

      - name: Sign artifacts
        run: |
          for f in dist/* provenance/sbom.spdx.json CHECKSUMS.SHA256; do
            gpg --batch --yes --armor --detach-sign "$f"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/*
            CHECKSUMS.SHA256*
            provenance/sbom.spdx.json*
