name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt || true
          pip install pytest pytest-cov ruff mypy
      - name: Lint (ruff)
        run: ruff check . || echo "ruff warnings"
      - name: Type check (mypy)
        run: mypy . || echo "mypy warnings"
      - name: Tests
        run: pytest -q
