name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools and deps (no package build)
        run: |
          python -m pip install --upgrade pip
          # якщо є requirements.txt/constraints.txt — встановимо
          if [ -f requirements.txt ]; then
            if [ -f constraints.txt ]; then
              pip install -r requirements.txt -c constraints.txt
            else
              pip install -r requirements.txt
            fi
          fi
          pip install pytest pytest-cov ruff mypy

      - name: Lint with ruff (non-blocking)
        run: ruff check . || echo "ruff warnings"

      - name: Type check with mypy (non-blocking)
        run: |
          if [ -d "btcmi" ]; then
            mypy btcmi || echo "mypy warnings"
          fi

      - name: Run tests with pytest
        env:
          PYTHONPATH: .
        run: pytest -q --disable-warnings --maxfail=1

      - name: Build docs
        run: |
          python scripts/generate_schema_docs.py
          mkdocs build --strict
