name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Generate SBOM
        run: python scripts/generate_sbom.py

      - name: Compute checksums
        run: |
          shasum -a 256 dist/* provenance/sbom.spdx.json > CHECKSUMS.SHA256

      - name: Generate signing key
        run: |
          gpg --batch --passphrase '' --quick-gen-key "CI <ci@example.com>" default default

      - name: Sign artifacts
        run: |
          for f in dist/* provenance/sbom.spdx.json CHECKSUMS.SHA256; do
            gpg --batch --yes --armor --detach-sign "$f"
          done

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            CHECKSUMS.SHA256*
            provenance/sbom.spdx.json*
